name: google_photos_internal_api_client
description: A client for accessing the Google Photos Internal API. Please note that Client for Google Photos Internal API is unofficial and not endorsed by Google.
version: 0.0.0
repository: https://github.com/tnc1997/dart-google-photos-internal-api-client

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
